version: '3.8'
services:
  app:
    container_name: portfolio
    build: .
    restart: unless-stopped
    networks: # <-- SEZIONE AGGIUNTA
      - web-proxy

networks: # <-- SEZIONE AGGIUNTA IN FONDO
  web-proxy:
    external: true